### ISSUE TITLE
Error while loading rule 'sukka/type/no-instanceof-wrapper': e.getScope is not a function

### ISSUE THREAD

**Issue by Innei** [SukkaW/eslint-config-sukka#5]
Hey, I'm trying to use this configuration and I'm having some problems. It's causing the most basic example to not work.

```

Oops! Something went wrong! :(

ESLint: 9.1.1

TypeError: Error while loading rule 'sukka/type/no-instanceof-wrapper': e.getScope is not a function
Occurred while linting /Users/innei/git/reproduction/eslint/eslint.config.mjs
    at create (file:///Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint-plugin-sukka@5.1.2_eslint@9.1.1_typescript@5.4.5/node_modules/eslint-plugin-sukka/dist/index.mjs:1:5853)
    at Object.create (file:///Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint-plugin-sukka@5.1.2_eslint@9.1.1_typescript@5.4.5/node_modules/eslint-plugin-sukka/dist/index.mjs:1:1124)
    at createRuleListeners (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:973:21)
    at /Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:1099:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:1031:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:1880:31)
    at Linter._verifyWithFlatConfigArray (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:2016:21)
    at Linter.verify (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:1505:61)
    at Linter.verifyAndFix (/Users/innei/git/reproduction/eslint/node_modules/.pnpm/eslint@9.1.1/node_modules/eslint/lib/linter/linter.js:2253:29)
```

My pnpm version is 

```
 pnpm -v
9.0.6
```

here is repro https://github.com/Innei/sukka-eslint-repro

**Comment by SukkaW** [comment]
@Innei Try updating to the `next` tag of `eslint-config-sukka`. The ESLint 9 supports are not released to the `latest` tag yet.

**Comment by Innei** [comment]
Another question: how do ignore some rules or customize some rules?

I try to change this. But every file ignored.

```ts

export default [
  sukka({
    ignores: {
      gitignore: true,
      customGlobs: ['assets/types/type.declare.ts'],
      enable: true,
    },
    node: true,
  }),
  { rules: {} },
]
```

```
...
/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/redis.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning

/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/safe-eval.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning

/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/schedule.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning

/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/system.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning

/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/time.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning

/Users/innei/git/innei-repo/mx-space/server-next/apps/core/src/utils/tool.util.ts
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning
```

Thanks for your reply
